### ISSUE TITLE
Internal Server Error `_send_verify_email(request, user)`

### ISSUE THREAD

**Issue by phase** [SpongePowered/SpongeAuth#230]
```
spongeauth_1  | [15/Sep/2018 15:04:45] "POST /accounts/register/ HTTP/1.1" 200 18607
spongeauth_1  | Internal Server Error: /accounts/register/
spongeauth_1  | Traceback (most recent call last):
spongeauth_1  |   File "/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
spongeauth_1  |     response = get_response(request)
spongeauth_1  |   File "/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
spongeauth_1  |     response = self.process_exception_by_middleware(e, request)
spongeauth_1  |   File "/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
spongeauth_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
spongeauth_1  |   File "/usr/lib/python3.6/contextlib.py", line 52, in inner
spongeauth_1  |     return func(*args, **kwds)
spongeauth_1  |   File "/app/spongeauth/accounts/views.py", line 247, in register
spongeauth_1  |     _send_verify_email(request, user)
spongeauth_1  |   File "/app/spongeauth/accounts/views.py", line 113, in _send_verify_email
spongeauth_1  |     html_message=msg_html,
spongeauth_1  |   File "/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 60, in send_mail
spongeauth_1  |     return mail.send()
spongeauth_1  |   File "/env/lib/python3.6/site-packages/django/core/mail/message.py", line 294, in send
spongeauth_1  |     return self.get_connection(fail_silently).send_messages([self])
spongeauth_1  |   File "/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
spongeauth_1  |     new_conn_created = self.open()
spongeauth_1  |   File "/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
spongeauth_1  |     self.connection = self.connection_class(self.host, self.port, **connection_params)
spongeauth_1  |   File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
spongeauth_1  |     (code, msg) = self.connect(host, port)
spongeauth_1  |   File "/usr/lib/python3.6/smtplib.py", line 336, in connect
spongeauth_1  |     self.sock = self._get_socket(host, port, self.timeout)
spongeauth_1  |   File "/usr/lib/python3.6/smtplib.py", line 307, in _get_socket
spongeauth_1  |     self.source_address)
spongeauth_1  |   File "/usr/lib/python3.6/socket.py", line 724, in create_connection
spongeauth_1  |     raise err
spongeauth_1  |   File "/usr/lib/python3.6/socket.py", line 713, in create_connection
spongeauth_1  |     sock.connect(sa)
spongeauth_1  | TimeoutError: [Errno 110] Connection timed out
spongeauth_1 | [15/Sep/2018 15:06:59] "POST /accounts/register/ HTTP/1.1" 500 126418
```
I'm not sure what is causing this. I'm using it in Docker.

**Comment by simon816** [comment]
```
spongeauth_1  |   File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
spongeauth_1  |     (code, msg) = self.connect(host, port)
...
spongeauth_1  | TimeoutError: [Errno 110] Connection timed out
```

Cannot connect to the SMTP server. You'll probably want to either create a test SMTP server or disable mail sending
